# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(null=True, upload_to='img/%Y/%m/%d', verbose_name='文章图片'),
        ),
    ]
