# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190507_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='ahaii', max_length=10, verbose_name='作者'),
        ),
    ]
